Web_dev/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.sdbuauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('detail/<course_id>', views.course_detail, name='course_detail'),
]

apps/course/models.py
from django.db import models

# Create your models here.

apps/course/views.py
from django.shortcuts import render


# Create your views here.
def course_index(request):
    return render(request, 'course/course_index.html')


def course_detail(request, course_id):
    return render(request, 'course/course_detail.html')

front/templates/course/course_detail.html
{% extends 'base/front_base.html' %}

{% block title %}
    在线课堂
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_detail.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业知识</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <div class="course-wrapper">
                <div class="course-info">
                    <p class="title">创业CEO如何避免技术决策错误</p>
                    <div class="price-group">
                        <div class="share-group">
                            <span class="course-title">分享至：</span>
                            <a class="weixin"></a>
                            <a href="#" class="weibo"></a>
                        </div>
                        <div class="buy-group">
                            <span class="price">免费</span>
                            <a href="#" class="buy-btn">立即购买</a>
                        </div>
                    </div>
                </div>
                <div class="video-group">

                </div>
            </div>
            <div class="bottom-wrapper">
                <div class="course-group">
                    <div class="item-group">
                        <p class="item-title">课程讲师</p>
                        <div class="teacher-group">
                            <div class="avatar">
                                <img src="https://static-image.xfz.cn/1536563248_165.png" alt="" class="avatar">
                            </div>
                            <div class="teacher-info">
                                <p class="teacher-name">龚世海</p>
                                <p class="teacher-desc">HiCTO创始人兼CEO</p>
                            </div>
                        </div>
                        <p class="item-content">
                            18年专注于品牌公关传播领域，是国内较早一批公关传播从业人员，曾供职于奥美、诺基亚、亚马逊、百事、戴尔、Uber等公司，亚马逊及Uber优步在中国的首任公关总监。
                        </p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">帮助中心</p>
                        <p class="item-content">1. 购买后的课程在线可反复观看学习，视频有效期以具体课程信息为准。<br>
                        2. 课程暂不支持下载观看，均为在线观看视频。<br>
                        3. 课程一经购买，不可转让、不可退款；仅限购买账号观看。<br>
                        4. 如有问题请咨询客服饭桌君： 电话：18618172287 微信：fanzhuojun888</p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程简介</p>
                        <p class="item-content">危机公关需要掌握好“度”——速度。</p>
                    </div>
                    <div class="item-group">
                        <p class="item-title">课程大纲</p>
                        <p class="item-content">1.面对危机公关，多快算快？<br>
                            2.面对危机公关，谁出面做解释和声明最有效？<br>
                            3.案例分析：戴尔和罗永浩<br>
                            4.危机公关，真的是“唯快不破”吗？</p>
                    </div>
                </div>
                <div class="recommend-wrapper">
                    <h3 class="recommend-title">推荐课程</h3>
                    <ul class="course-list">
                        <li class="course-detail">
                            <div class="course-info">
                                <p class="course-name">公关需要对营销“尺度”进行把控</p>
                                <p class="teacher">高超/资深品牌公关</p>
                            </div>
                            <div class="course-image">
                                <img src="https://static-image.xfz.cn/1563171906_23.png-course.list.small" alt="" class="course-image">
                            </div>
                        </li>
                        <li class="course-detail">
                            <div class="course-info">
                                <p class="course-name">创业中如何进行风险管理</p>
                                <p class="teacher">贺伊韩/未来法律CEO</p>
                            </div>
                            <div class="course-image">
                                <img src="https://static-image.xfz.cn/1497870564_403.jpg-course.list.small" alt="" class="course-image">
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/course/course_index.html
{% extends 'base/front_base.html' %}

{% block title %}
    在线课堂
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/course/course_index.min.css' %}">
{% endblock %}

{% block main %}
    <div class="main">
        <div class="course-nav">
            <div class="nav-container">
                <h3 class="title">在线课堂</h3>
                <ul class="nav-list">
                    <li class="active"><a href="#">最新课堂</a></li>
                    <li><a href="#">投资人说</a></li>
                    <li><a href="#">明星案例</a></li>
                    <li><a href="#">创业知识</a></li>
                </ul>
            </div>
        </div>
        <div class="wrapper">
            <ul class="course-list">
                <li>
                    <a href="{% url 'course:course_detail' course_id=78 %}">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1563171621_723.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">创业CEO如何避免技术决策错误</p>
                            <p class="author">龚世海/HiCTO创始人兼CEO</p>
                            <p class="price-tag">
                                <span class="free">免费</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1563171954_878.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">面对危机公关，多快算快？</p>
                            <p class="author">高超 / 资深品牌公关</p>
                            <p class="price-tag">
                                <span class="pay">$0.99</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1526455098_289.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">教你抓住投资人眼球的计划书。</p>
                            <p class="author">李喆 / 远瞻资本创始合伙人、总裁 、上海科委特约专家</p>
                            <p class="price-tag">
                                <span class="free">免费</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1513066370_185.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">Innovation in intelligence systems</p>
                            <p class="author">Yosi Lahad /  Co-Founder of NextWave Roboti</p>
                            <p class="price-tag">
                                <span class="pay">￥19.90</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1563169011_412.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">创业公司如何找钱？</p>
                            <p class="author">王钊 / Hi-Finance创始人兼CEO</p>
                            <p class="price-tag">
                                <span class="pay">￥59.00</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="thumbnail">
                            <img src="https://static-image.xfz.cn/1563169011_412.png-course.list.small" alt="">
                        </div>
                        <div class="course-info">
                            <p class="title">创业公司如何找钱？</p>
                            <p class="author">王钊 / Hi-Finance创始人兼CEO</p>
                            <p class="price-tag">
                                <span class="pay">￥59.00</span>
                            </p>
                        </div>
                    </a>
                </li>
                <li></li>
                <li></li>
            </ul>
        </div>
    </div>
{% endblock %}