Web_dev/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.sdbuauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='cms_index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
]

apps/sdbuauth/urls.py
from django.urls import path
from . import views

app_name = 'sdbuauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('register/', views.register, name='register'),
    # 测试memcached
    # path('cache/', views.cache_text, name='cache_test'),
]

apps/cms/models.py
from django.db import models


# Create your models here.

apps/cms/forms.py
from django import forms
from apps.forms import FormMixin
from apps.news.models import News


class EditNewsCategoryForm(forms.Form, FormMixin):
    pk = forms.IntegerField()
    name = forms.CharField(max_length=20)


class NewsForm(forms.ModelForm, FormMixin):
    category = forms.IntegerField()

    class Meta:
        model = News
        exclude = ['category', 'pub_time', 'author']

apps/cms/views.py
import os
from django.views import View
from django.shortcuts import render
from django.contrib.admin.views.decorators import staff_member_required
from django.views.decorators.http import require_POST, require_GET
from apps.news.models import NewsCategory, News
from utils import restful
from .forms import EditNewsCategoryForm, NewsForm
from django.conf import settings


# Create your views here.
# django自带的验证是否位员工的装饰器
@staff_member_required(login_url='index')
def index(request):
    return render(request, 'cms/index.html')


class WriteNewsView(View):

    def get(self, request):
        categories = NewsCategory.objects.all()
        context = {'categories': categories}
        return render(request, 'cms/write_news.html', context=context)

    def post(self, request):
        form = NewsForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            desc = form.cleaned_data.get('desc')
            thumbnail = form.cleaned_data.get('thumbnail')
            content = form.cleaned_data.get('content')
            category_id = form.cleaned_data.get('category')
            category = NewsCategory.objects.get(pk=category_id)
            # 测试用
            # print(title, desc, thumbnail)
            news = News.objects.create(title=title, desc=desc, thumbnail=thumbnail, content=content, category=category, author=request.user)
            return restful.ok()
        else:
            return restful.params_error(message=form.get_errors())


@require_GET
def news_category(request):
    categories = NewsCategory.objects.all()
    context = {'categories': categories}
    return render(request, 'cms/news_category.html', context=context)


@require_POST
def add_news_category(request):
    name = request.POST.get('name')
    exists = NewsCategory.objects.filter(name=name).exists()
    if not exists:
        NewsCategory.objects.create(name=name)
        return restful.ok()
    else:
        return restful.params_error(message='该分类已经存在。')


@require_POST
def edit_news_category(request):
    form = EditNewsCategoryForm(request.POST)
    if form.is_valid():
        pk = form.cleaned_data.get('pk')
        name = form.cleaned_data.get('name')
        try:
            NewsCategory.objects.filter(pk=pk).update(name=name)
            return restful.ok()
        except:
            return restful.params_error(message='该新闻分类不存在。')
    else:
        return restful.params_error(message=form.get_errors())


@require_POST
def delete_news_category(request):
    pk = request.POST.get('pk')
    exists = NewsCategory.objects.filter(pk=pk).exists()
    if exists:
        try:
            NewsCategory.objects.get(pk=pk).delete()
            return restful.ok()
        except:
            return restful.params_error(message='当前分类不存在。')
    else:
        return restful.params_error(message='当前分类不存在。')


@require_POST
def upload_file(request):
    file = request.FILES.get('file')
    name = file.name
    with open(os.path.join(settings.MEDIA_ROOT + '/' + name), 'wb') as fp:
        for chunk in file.chunks():
            fp.write(chunk)
    # build_absolute_uri()继承了域名以及端口号等信息
    url = request.build_absolute_uri(settings.MEDIA_URL + name)
    return restful.result(data={'url': url, })

front/templates/cms/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}{% endblock %} | SdBU后台管理系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet"
          href="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/plugins/summernote/summernote-bs4.css' %}">
    <link rel="stylesheet" href="{% static 'sweetalert/sweetalert.css' %}">

    <script src="{% static 'adminlte/plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/jquery-ui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script>
        $.widget.bridge('uibutton', $.ui.button)
    </script>
    <script src="{% static 'adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/summernote/summernote-bs4.min.js' %}"></script>
    <script src="{% static 'adminlte/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/adminlte.js' %}"></script>
    <script src="{% static 'adminlte/dist/js/pages/dashboard.js' %}"></script>
    <script src="{% static 'js/sdbuajax.min.js' %}"></script>
    <script src="{% static 'sweetalert/sweetalert.min.js' %}"></script>
    <script src="{% static 'js/sdbualert.min.js' %}"></script>
    {% block head %}
    
    {% endblock %}
</head>
<body class="hold-transition sidebar-mini layout-fixed">
<div class="wrapper">

    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'index' %}" class="nav-link">首页</a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <a href="#" class="nav-link">Contact</a>
            </li>
        </ul>
    </nav>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'cms:cms_index' %}" class="brand-link">
            <span class="brand-text font-weight-light"><b>SdBU</b> | CMS</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{% static 'images/logo.jpeg' %}" class="img-circle elevation-2" alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">SdBU034</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item has-treeview">
                        <a href="{% url 'cms:cms_index' %}" class="nav-link">
                            <i class="fa fa-home nav-icon"></i>
                            <p>首页</p>
                        </a>
                    </li>
                    <li class="nav-header">新闻管理</li>
                    <li class="nav-item has-treeview">
                        <a href="{% url 'cms:write_news' %}" class="nav-link">
                            <i class="fa fa-edit nav-icon"></i>
                            <p>发布新闻</p>
                        </a>
                    </li>
                    <li class="nav-item has-treeview">
                        <a href="{% url 'cms:news_category' %}" class="nav-link">
                            <i class="fa fa-calendar-check nav-icon"></i>
                            <p>新闻分类</p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <div class="content-header">
            {% block content-header %}{% endblock %}
        </div>
        <section class="content">
            {% block content %}{% endblock %}
        </section>
        <!-- /.content -->
    </div>

    <footer class="main-footer">
        <b>SdBU后台管理系统</b>
    </footer>

</div>

</body>
</html>

front/templates/cms/index.html
{% extends 'cms/base.html' %}

{% block title %}
    首页
{% endblock %}

{% block content-header %}
    <h1 style="margin: 10px 0 10px 20px">后台管理首页</h1>
{% endblock %}

front/templates/cms/login.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>SdBU034 | 登录</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'css/adminlte/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'css/adminlte/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'css/adminlte/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="#"><b>SdBU034</b>登录</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <p class="login-box-msg">请登录</p>

      <form action="{% url 'sdbuauth:login' %}" method="post">
          {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="手机号码" name="telephone">
          <div class="input-group-append">
            <div class="input-group-text">
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" class="form-control" placeholder="密码" name="password">
          <div class="input-group-append">
            <div class="input-group-text">
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember" name="remember" value="1">
              <label for="remember">
                记住密码
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">登录</button>
          </div>
          <!-- /.col -->
        </div>
      </form>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'js/adminlte.min.js' %}"></script>

</body>
</html>

front/templates/cms/news_category.html
{% extends 'cms/base.html' %}

{% block title %}
    新闻分类
{% endblock %}

{% block head %}
    <script src="{% static 'js/news_category.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1 style="margin: 10px 0 10px 20px">新闻分类</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <div class="card">
              <div class="card-header">
                  <button class="btn btn-primary float-right" id="add-category">添加分类</button>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>分类名</th>
                      <th>新闻数量</th>
                      <th style="width: 200px">操作</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for category in categories %}
                        <tr data-pk="{{ category.pk }}" data-name="{{ category.name }}">
                            <td>{{ forloop.counter }}.</td>
                            <td>{{ category.name }}</td>
                            <td>44</td>
                            <td>
                                <button type="button" class="btn btn-success btn-xs edit-new-category">编辑</button>
                                <button type="button" class="btn btn-danger btn-xs delete-new-category">删除</button>
                            </td>
                        </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
              <div class="card-footer clearfix">
                <ul class="pagination pagination-sm m-0 float-right">
                  <li class="page-item"><a class="page-link" href="#">«</a></li>
                  <li class="page-item"><a class="page-link" href="#">1</a></li>
                  <li class="page-item"><a class="page-link" href="#">2</a></li>
                  <li class="page-item"><a class="page-link" href="#">3</a></li>
                  <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
              </div>
            </div>
        </div>
    </div>
{% endblock %}

front/templates/cms/write_news.html
{% extends 'cms/base.html' %}

{% block title %}
    发布新闻
{% endblock %}

{% block head %}
    <script src="{% static 'ueditor/ueditor.config.js' %}"></script>
    <script src="{% static 'ueditor/ueditor.all.min.js' %}"></script>
    <script src="{% static 'js/write_news.min.js' %}"></script>
{% endblock %}

{% block content-header %}
    <h1 style="margin: 10px 0 10px 20px">发布新闻</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <!-- left column -->
        <div class="col-md-12">
        <!-- general form elements -->
            <div class="card card-primary">
                <!-- form start -->
                <form role="form">
                    <div class="card-body">
                        <div class="form-group">
                            <label for="InputTitle">标题</label>
                            <input type="text" class="form-control" id="InputTitle" placeholder="输入标题" name="title">
                        </div>

                        <div class="form-group">
                            <label for="category-form">分类</label>
                            <select class="form-control" id="category-form" name="category">
                                {% for category in categories %}
                                    <option value="{{ category.pk }}">{{ category.name }}</option>
                                {% endfor %}
                            </select>
                        </div>

                        <div class="form-group">
                            <label for="InputDesc">描述</label>
                            <input type="text" class="form-control" id="InputDesc" placeholder="输入描述" name="desc">
                        </div>

                        <div class="form-group">
                            <label for="InputImage">缩略图</label>
                            <div class="input-group">
                                <input type="text" class="form-control" id="InputImage" placeholder="输入缩略图url" name="thumbnail">
                                <span class="input-group-btn">
                                    <label for="thumbnail-btn" class="btn btn-default btn-file">上传图片<input hidden class="btn btn-default" type="file" id="thumbnail-btn"></label>
                                </span>
                            </div>
                        </div>

                        <div class="form-group">
                            <label>内容</label>
                            <script id="editor" type="text/plain"></script>
                        </div>

                        <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Check me out</label>
                        </div>
                    </div>
                    <!-- /.card-body -->

                    <div class="card-footer">
                        <button type="submit" class="btn btn-primary" id="submit-btn">发布</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}