Web_dev/urls.py
from django.urls import path, include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name='index'),
    path('news/', include('apps.news.urls')),
    path('cms/', include('apps.cms.urls')),
    path('account/', include('apps.sdbuauth.urls')),
    path('course/', include('apps.course.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cms/urls.py
from django.urls import path
from . import views

app_name = 'cms'

urlpatterns = [
    path('', views.index, name='cms_index'),
    path('write_news/', views.WriteNewsView.as_view(), name='write_news'),
    path('news_category/', views.news_category, name='news_category'),
    path('add_news_category/', views.add_news_category, name='add_news_category'),
    path('edit_news_category/', views.edit_news_category, name='edit_news_category'),
    path('delete_news_category/', views.delete_news_category, name='delete_news_category'),
    path('upload_file/', views.upload_file, name='upload_file'),
]

apps/course/urls.py
from django.urls import path
from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_index, name='course_index'),
    path('detail/<course_id>', views.course_detail, name='course_detail'),
]

apps/sdbuauth/urls.py
from django.urls import path
from . import views

app_name = 'sdbuauth'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('img_captcha/', views.img_captcha, name='img_captcha'),
    path('register/', views.register, name='register'),
    # 测试memcached
    # path('cache/', views.cache_text, name='cache_test'),
]

front/templates/base/front_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
    
    {% endblock %}</title>
    <link rel="stylesheet" href="//at.alicdn.com/t/font_1898405_5f7h3pkfzzu.css">
    <link rel="stylesheet" href="{% static 'css/common/auth.min.css' %}">
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'js/message.min.js' %}"></script>
    <script src="{% static 'js/sdbuajax.min.js' %}"></script>
    <script src="{% static 'js/front_base.min.js' %}"></script>
    {% block head %} {% endblock %}
</head>

<body>
    <header class="header">
        <div class="container">
            <div class="logo_box">
                <a href="/">SdBU034</a>
            </div>

            <ul class="nav">
                <li class="active"><a href="/">创业资讯</a></li>
                <li><a href="{% url 'course:course_index' %}">创业课堂</a></li>
                <li><a href="#">付费资讯</a></li>
                <li><a href="#">搜索</a></li>
            </ul>

            <div class="auth-box">
                <i class="icon-person_crop_circle iconfont"></i>
                {% if user.is_authenticated %}
                    <a href="#" class="authenticated-box">{{ user.username }}</a>
                    <div class="user-more-box">
                        <i class="triangle"></i>
                        {% if user.is_staff %}
                            <a href="{% url 'cms:cms_index' %}">管理系统</a>
                        {% endif %}
                        <a href="{% url 'sdbuauth:logout' %}">退出登录</a>
                    </div>
                {% else %}
                    <a href="#">登陆/注册</a>
                {% endif %}

            </div>
        </div>
    </header>

    {% block main %}
    
    {% endblock %}

    <footer class="footer">
        <div class="top-group">
            <div class="inner-group">
                <div class="logo-box"></div>
                <div class="detail-group">
                    <div class="line-one">
                        <ul class="links">
                            <li><a href="#">关于SdBU034</a></li>
                            <li><a href="#">创业课堂</a></li>
                            <li><a href="#">寻求报道</a></li>
                            <li><a href="#">创业礼包</a></li>
                        </ul>
                        <div class="about-us">
                            <span class="title">关于我们：</span>
                            <ul class="social">
                                <li class="wechat">
                                    <div class="wx-qrcode"></div>
                                    <a href="#" class="text">SdBU034</a>
                                </li>
                                <li class="weibo"><a href="#" class="text">SdBU034</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="line-two">
                        <p class="address">地址：山东省济南市市中区二环东路11896号</p>
                        <p class="contact">联系方式：400-810-1090（工作日10点-18点）</p>
                    </div>
                </div>
            </div>
        </div>
        <div class="bottom-group">
            ©2020 北京子木投资顾问有限公司 京ICP备15051289号 | 增值电信业务经营许可证：京B2-20170574
        </div>
    </footer>
    <div class="mask-wrapper">
        <div class="auth-wrapper">
            <div class="close-wrapper">
                <span class="close-btn icon-close iconfont"></span>
            </div>
            <div class="auth-inner-wrapper">
                <div class="scroll-wrapper">
                    <div class="login auth-group">
                        <div class="top-group">
                            <span class="title">请登录</span>
                            <a href="javascript: void(0);" class="switch">立即注册></a>
                        </div>
                        <div class="form-group">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="password" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <label class="remember-label"><input type="checkbox" name="remember" value="1">记住我</label>
                            </div>
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即登录">
                            </div>
                        </div>
                    </div>
                    <div class="register auth-group">
                        <div class="top-group">
                            <span class="title">请注册</span>
                            <a href="javascript: void(0);" class="switch">立即登录></a>
                        </div>
                        <div class="form-group">
                            {% csrf_token %}
                            <div class="input-group">
                                <input type="text" class="form-control" name="telephone" placeholder="手机号码">
                            </div>
                            <div class="input-group">
                                <input type="text" class="form-control" name="username" placeholder="用户名">
                            </div>
                            <div class="input-group">
                                <div class="short-input-group">
                                    <input type="text" class="form-control" name="img_captcha" placeholder="图形验证码">
                                </div>
                                <div class="iuput-group-addon" style="cursor: pointer">
                                    <img src="{% url 'sdbuauth:img_captcha' %}" alt="" class="img-captcha">
                                </div>
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="pwd1" placeholder="密码">
                            </div>
                            <div class="input-group">
                                <input type="password" class="form-control" name="pwd2" placeholder="确认密码">
                            </div>
{#                            <div class="input-group">#}
{#                                <div class="short-input-group">#}
{#                                    <input type="text" class="form-control" name="sms-captcha" placeholder="短信验证码">#}
{#                                </div>#}
{#                                <div class="iuput-group-addon">#}
{#                                    <button class="sms-captcha-btn">发送验证码</button>#}
{#                                </div>#}
{#                            </div>#}
                            <div class="input-group">
                                <input type="submit" class="submit-btn" value="立即注册">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>